### ISSUE TITLE
Developing a Framework for the 2018 Update of The People's Roadmap to a Digital New York City

### ISSUE THREAD

**Issue by lbrennee** [mozilla/global-sprint#178]
**[ Project Contact ]** @betanyc 
**[ GitHub Repo ]** https://github.com/BetaNYC/ops-roadmap
**[ Track ]** Digital Inclusion, 
**[ Location ]** New York City, Eastern Time. 

### Description
_The People’s Roadmap to a Digital New York City_ is a citizen-created policy document that provides short-term recommendations to guide the use of technology by government. The Roadmap is being updated in 2018 to include new policies, projects, and potential partnerships to address community identified issues surrounding the digital future of New York City. This project focuses on developing a framework to facilitate the 2018 update that allows for greater participation and transparency.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @lbrennee & @betanyc 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by bchrobot** [comment]
- [x] GitHub repo: https://github.com/BetaNYC/peoples-roadmap-2018
- [x] README: https://github.com/BetaNYC/peoples-roadmap-2018/blob/master/README.md
- [x] LICENSE: https://github.com/BetaNYC/peoples-roadmap-2018/blob/master/LICENSE.md
- [x] `mozsprint` issues: https://github.com/BetaNYC/peoples-roadmap-2018/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint
